title: Geospatial Observation and Applications Lab (GOAL)
description: "Research in geospatial analysis, remote sensing, and hydrological modeling."
remote_theme: "mmistakes/minimal-mistakes"  # Applying Minimal Mistakes theme
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap

# Site Settings
name: "GOAL Lab"
author:
  name: "Dr. Shanti Shwarup Mahto"
  email: "ssmahto.clim@gmail.com"

# Navigation (Modify this based on your needs)
nav:
  - title: "Home"
    url: /
  - title: "Research"
    url: /research/
  - title: "Publications"
    url: /publications/
  - title: "Team"
    url: /team/
  - title: "Contact"
    url: /contact/

# Social Links (Optional)
social:
  github: your-github-username
  twitter: your-twitter-handle
  linkedin: https://www.linkedin.com/in/shanti-shwarup-mahto-phd-490422121/
  personal: https://sites.google.com/view/dr-ssmahto/monitoring-and-early-warning
  
# Custom Stylesheet
sass:
  sass_dir: _sass
  style: compressed

include:
  - "assets/css/custom.css"
