title: "GOAL: Geospatial Observations and Application Lab"
description: "Research in hydroclimatic studies, remote sensing, and GIS."
baseurl: "/lab-website"  # Set this to your repository name
url: "https://GOALCUJ.github.io"  # Your GitHub Pages domain

navbar-links:
  Home: "index.html"
  About: "about.html"
  Research: "research.html"
  Publications: "publications.html"
  Team: "team.html"
  Opportunities: "opportunities.html"
  Contact: "contact.html"

theme: minima  # You can replace this with any Jekyll theme you prefer.
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
